# Realización de ejercicios de Tratamiento de Datos

3.1 Lectura formateada de datos en R.

In [1]:
## Vamos a establecer el directorio
setwd("/home/jovyan/work/tratamiento")

## Luego para poner la Tabla de datos Empleados.csv en un "DataFrame" se usa función read.table
Datos<-read.table("Empleados.csv",header=TRUE, sep=",",dec=".",row.names=1)
Datos

Sexo EstadoCivil Nacionalidad Edad Nivel
Juan      H    Casado      Mexicano     40   1    
Hugo      H    Soltero     Mexicano     36   2    
Laura     M    Soltera     Argentina    28   1    
Ramon     H    Casado      Chileno      60   3    
Antonio   H    Casado      Uruguayo     33   3    
Sofia     M    Casada      China        29   2    
Alejandra M    Soltera     Alemana      44   1    
Alfredo   H    Soltero     Uruguayo     53   1    
Romina    M    Casada      Chilena      38   2    
Felipe    H    Casado      Mexicano     28   2

La función summary permite hacer una exploración inicial de los datos, hace un resumen estadístico, mostrando el valor, mínimo, primer quartil, la mediana, la media el tercer quartil y el valor máximo.


In [2]:
summary(Datos)


 Sexo   EstadoCivil    Nacionalidad      Edad          Nivel    
 H:6   Casada :2    Alemana  :1     Min.   :28.0   Min.   :1.0  
 M:4   Casado :4    Argentina:1     1st Qu.:30.0   1st Qu.:1.0  
       Soltera:2    Chilena  :1     Median :37.0   Median :2.0  
       Soltero:2    Chileno  :1     Mean   :38.9   Mean   :1.8  
                    China    :1     3rd Qu.:43.0   3rd Qu.:2.0  
                    Mexicano :3     Max.   :60.0   Max.   :3.0  
                    Uruguayo :2                                 

Para leer el mismo archivo pero ahora con formato .txt se hace lo siguiente:


In [3]:
## Vamos a establecer el directorio
setwd("/home/jovyan/work/tratamiento")

DatosTexto<-read.table("Empleados.txt",header=TRUE, sep="\t",dec=".",row.names=1)
DatosTexto

Sexo EstadoCivil Nacionalidad Edad
Juan      H    Casado      Mexicano     40  
Hugo      H    Soltero     Mexicano     36  
Laura     M    Soltera     Argentina    28  
Ramon     H    Casado      Chileno      60  
Antonio   H    Casado      Uruguayo     33  
Sofia     M    Casada      China        29  
Alejandra M    Soltera     Alemana      44  
Alfredo   H    Soltero     Uruguayo     53  
Romina    M    Casada      Chilena      38  
Felipe    H    Casado      Mexicano     28

## 3.2 Eliminar valores.

En R existe un objeto para representar a los valores ausentes llamado NA, cuando se aplican funciones sobre datos con valores NA, los resultados de éstas funciones siempre serán NA. En R, la mayoría de las funciones matemáticas para evitar esto, tienen el parámetro na.rm, que al asignarle el valor true, se le indica a la función que ignore todos los valores Na encontrados en los datos.


In [4]:
vector_1 <- c(0,1,2,3,4,5,6,NA,8,NA,9,10)
vector_1

[1]  0  1  2  3  4  5  6 NA  8 NA  9 10

In [5]:
#Ignorando los valres NA con la función na.rm
mean(vector_1)

[1] NA

In [6]:
mean(vector_1, na.rm = TRUE)

[1] 4.8

## 3.3 Variables indexadas y matrices.

Las matrices son un tipo especial de vectores con 2 dimensiones, representadas de forma rectángular por filas y columnas.
En R se pueden crear matrices con la función matrix() que utiliza 4 parámetros para su configuración, estos parámetros son los siguientes:
data: vector con los datos que contendrá la matriz.
nrow: cantidad de filas o renglones que contendrá la matriz
ncol: cantidad de columnas en la matriz
byrow: especifica cómo será la lectura de los datos en la matriz, si su valor es TRUE la lectura se realiza por filas, de los contrario se leerá por columnas.
Ejemplo

In [7]:
##Lectura por renglones o filas
matriz_1<-matrix(c(1,2,3,4,5,6,7,8,9,10,11,12),nrow=4, ncol=3, byrow = T)
matriz_1

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [8]:
## Lectura por columnas
matriz_2<-matrix(c(1,2,3,4,5,6,7,8,9,10,11,12),nrow=4, ncol=3, byrow = F)
matriz_2

[,1] [,2] [,3]
[1,] 1    5     9  
[2,] 2    6    10  
[3,] 3    7    11  
[4,] 4    8    12

Para hacer consultas por fila o por columna de la matriz, se hace a traves de los corchetes [,], el valor antes de la coma indica en número de fila y el valor despues de la coma indica el valor de la columna.
Ejemplo:

In [9]:
matriz_1<-matrix(c(1,2,3,4,5,6,7,8,9,10,11,12),nrow=4, ncol=3, byrow = T)
matriz_1

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [10]:
## Para consultar un valor específico
matriz_1[3,3]

[1] 9

In [11]:
## [1] 9

In [12]:
## Para consultar los valores de la columna 1
matriz_1[,1]

[1]  1  4  7 10

In [13]:
## Para consultar los valores del renglón 2
matriz_1[2,]

[1] 4 5 6

In [14]:
## Para consultar los valores de las columnas 1 y 2
matriz_1[,1:2]

[,1] [,2]
[1,]  1    2  
[2,]  4    5  
[3,]  7    8  
[4,] 10   11

In [15]:
## Para consultar los valores de los renglones 1 a 3
matriz_1[1:3,]

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

In [16]:
##Para conocer las dimensiones de una matriz es con la función dim
dim(matriz_1)


[1] 4 3

Combinación de matrices.
Las funciones cbind() y rbind() se pueden usar para unir dos o más vectores o matrices, por columnas o por filas, respectivamente, como se puede observar en los siguientes ejemplos:

In [17]:
## Primera matriz 
m1 <- matrix(c(45, 23, 66, 77, 33, 44, 56, 12, 78, 23), 2,5)
m1

[,1] [,2] [,3] [,4] [,5]
[1,] 45   66   33   56   78  
[2,] 23   77   44   12   23

In [18]:
## Segunda matriz
m2 <- matrix(rep(10, 20), 2, 5)
m2

[,1] [,2] [,3] [,4] [,5]
[1,] 10   10   10   10   10  
[2,] 10   10   10   10   10

In [19]:
## la matriz m2 se coloca debajo de la matriz m1
m3 <- rbind(m1,m2)
m3

[,1] [,2] [,3] [,4] [,5]
[1,] 45   66   33   56   78  
[2,] 23   77   44   12   23  
[3,] 10   10   10   10   10  
[4,] 10   10   10   10   10

In [20]:
 dim(m3)

[1] 4 5

In [21]:
## la matriz m2 se coloca después de la matriz m1
m3 <- cbind(m1,m2)
m3

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,] 45   66   33   56   78   10   10   10   10   10   
[2,] 23   77   44   12   23   10   10   10   10   10

In [22]:
dim(m3)

[1]  2 10

 3.4. Listas, hojas de datos (Data Frames) y subconjuntos de datos.
Listas en R.
Una lista, en R, es una clase de datos que puede contener cero o más elementos, cada uno de los cuales puede ser de una clase distinta.
Por ejemplo, si se considera la tabla de empleados, como una base de datos, donde cada empleado, tiene los atributos de Sexo, EstadoCivil, Nacionalidad, Edad y Nivel. Se podría iniciar una lista vacía como sigue:

In [23]:
## Se crea la lista vacía emp con la función list()
emp <- list()

##Para insertar el primer empleado se puede hacer como sigue:

emp <- list(Nombre="Ana", Sexo="M", EstadoCivil="Soltera", Nacionalidad="Argentina", Edad= 49, Nivel=1)
emp

$Nombre
[1] "Ana"

$Sexo
[1] "M"

$EstadoCivil
[1] "Soltera"

$Nacionalidad
[1] "Argentina"

$Edad
[1] 49

$Nivel
[1] 1

In [24]:
## Aunque, las etiquetas de los elementos, por ejemplo, "Nombre", son opcionales, también se puede hacer:

emp2 <- list("Mónica", "M", "Casada", "Española", 32, Nivel=4)
emp2

[[1]]
[1] "Mónica"

[[2]]
[1] "M"

[[3]]
[1] "Casada"

[[4]]
[1] "Española"

[[5]]
[1] 32

$Nivel
[1] 4

Los nombres de los elementos en una lista se llaman “tags”. Estos se pueden obtener con el operador “names()”:


In [25]:
names(emp)

[1] "Nombre"       "Sexo"         "EstadoCivil"  "Nacionalidad" "Edad"        
[6] "Nivel"

Para obtener los valores se usa “unlist()”:


In [26]:
ulemp  <- unlist(emp)
ulemp

Nombre         Sexo  EstadoCivil Nacionalidad         Edad        Nivel 
       "Ana"          "M"    "Soltera"  "Argentina"         "49"          "1"

El retorno de “unlist()” es un vector modo carácter, o sea, un vector de “strings”.
Las listas de R tienen cierta semejanza a los “struct” del lenguaje C, por ejemplo, una lista x con dos elementos


In [27]:
x <- list(abc="Luis",  de=5)
x

$abc
[1] "Luis"

$de
[1] 5

Así la lista x tiene dos elementos:


In [28]:
x$abc


[1] "Luis"

In [29]:
x$de


[1] 5

El operador “$” en R funciona como el operador “.” en C.


In [30]:
names(x)


[1] "abc" "de"

In [31]:
ulx <-  unlist(x)
x

$abc
[1] "Luis"

$de
[1] 5

In [32]:
class(ulx)


[1] "character"

Subconjuntos de datos.
Una de las principales tareas del procesamiento de datos es crear subconjuntos de datos, para su posterior análisis.
En R tres de los operadores que permiten crear subconjuntos, son: $, [[]], [].
El símbolo $ se utiliza para designar elementos con nombre de una lista, pero también [[ ]] trabaja para hacer referencia a un solo elemento.
Recordando que emp está definido por
emp <- list(Nombre=“Ana”, Sexo=“M”, EstadoCivil=“Soltera”, Nacionalidad=“Argentina”, Edad= 49, Nivel=1)
entonces:

In [33]:
emp <- list(Nombre="Ana", Sexo="M", EstadoCivil="Soltera", Nacionalidad="Argentina", Edad= 49, Nivel=1)
emp

$Nombre
[1] "Ana"

$Sexo
[1] "M"

$EstadoCivil
[1] "Soltera"

$Nacionalidad
[1] "Argentina"

$Edad
[1] 49

$Nivel
[1] 1

In [34]:
emp$Nacionalidad

[1] "Argentina"

In [35]:
emp[[3]]

[1] "Soltera"

Hojas de datos o Data Frames.
Un Data Frame u hoja de datos,es una lista cuyos componentes pueden ser vectores, matrices o factores.
Son la manera más eficiente mediante la cual R, puede analizar estadísticamente un conjunto de datos. Los Data Frames se configuran de tal manera que cada fila se refiere a un individuo y cada columna hace referencia a una variable que define al individuo.
Esta configuración hace que visualmente una hoja de datos o Data Frame parezca una matriz. Sin embargo, como objetos de R, son cosas distintas. Por ejemplo para construir un Data Frame con los datos de 3 personas, que incluyan el color de ojos, peso y altura. Se debe hcer el siguiente procedimiento:

In [36]:
# Se inicia definiendo el color de los ojos:
ojos<-factor(c("Azules","Marrones","Marrones"), levels=c("Azules","Marrones","Verdes","Negros"))
ojos

[1] Azules   Marrones Marrones
Levels: Azules Marrones Verdes Negros

In [37]:
## Suponiendo que los peso son, 68, 75, 88 y las alturas 1.65, 1.79, 1.85 respectivamente. Entonces, se define la hoja de datos mediante:

datos<-data.frame(Color.ojos=ojos,Peso=c(68,75,88),Altura=c(1.65,1.79,1.85))
datos

Color.ojos Peso Altura
1 Azules     68   1.65  
2 Marrones   75   1.79  
3 Marrones   88   1.85

In [38]:
##Así, se tienen tres variables, llamadas Color.ojos, Peso y Altura. 

## Medinte el comando str se puede ver la estructura y tipos del Data Frame:
## Con la función str(datos) se muestra, que Color.ojos es una variable de tipo factor, peso y altura son variables numéricas. 
str(datos)

'data.frame':	3 obs. of  3 variables:
 $ Color.ojos: Factor w/ 4 levels "Azules","Marrones",..: 1 2 2
 $ Peso      : num  68 75 88
 $ Altura    : num  1.65 1.79 1.85


In [39]:
## También se puede convertir una matriz en una hoja de datos mediante la función as.data.frame. 
## Por ejemplo la siguiente instrucción convertirá la matriz d en una hoja de datos.

m1<-matrix(c(1,2,3,4,5,6,7,8,9,10,11,12),nrow=4, ncol=3, byrow = T)
m1

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

In [40]:
datos2<-as.data.frame(m1)
datos2

V1 V2 V3
1  1  2  3
2  4  5  6
3  7  8  9
4 10 11 12

In [41]:
##Si se quiere consultar los nombres con los que quedaron las variables se hace con names(datos2):
names(datos2)

[1] "V1" "V2" "V3"

In [42]:
## Pero se puede modificar usando la función names(), forzando la asignación como sigue:

names(datos2)<-c("Variable 1","Variable 2","Variable 3")
datos2

Variable 1 Variable 2 Variable 3
1  1          2          3        
2  4          5          6        
3  7          8          9        
4 10         11         12

In [43]:
## Pero se puede modificar usando la función names(), forzando la asignación como sigue:

names(datos2)<-c("Variable 1","Variable 2","Variable 3")
datos2

Variable 1 Variable 2 Variable 3
1  1          2          3        
2  4          5          6        
3  7          8          9        
4 10         11         12

Existen dos maneras para poder acceder a los elementos de una hoja de datos:
a) Usando el mismo método que para las matrices.
b) Usando el operador $ por ejemplo para obtener los datos de la variable Color.ojos, se escribe:

In [44]:
datos$Color.ojos


[1] Azules   Marrones Marrones
Levels: Azules Marrones Verdes Negros

Las funciones nrow() y ncol() sirven Para conocer el número de filas y de columnas de una hoja de datos.


In [45]:
ncol(datos)


[1] 3

In [46]:
nrow(datos)


[1] 3

 Para estar seguros qué tipo de datos son con los que se esta trabajando, en R existen funciones, que pueden informar sobre el tipo de los objetos.
Las funciones, is.vector() para vectores, is.matrix() para matrices y la función is.data.frame() para los Data Frames, respectivamente. Indican el tipo de datos que confirma o rechaza la consulta. Si el resultado de la función es verdadero, se trata del tipo de objeto consultado, en caso contrario el resultado de la función será False.
O bien se puede utilizar el operador class que devuelve directamente la clase a la que pertenece el objeto o instancia. Por ejemplo:

In [47]:
class(m1)


[1] "matrix"

In [48]:
class(datos) 


[1] "data.frame"

In [49]:
class(x)

[1] "list"

## 3.5. Lectura de datos de un fichero
Como se mostró en un ejemplo anterior se pueden leer datos de un fichero, con la función read.table.


In [50]:
Datos<-read.table("Empleados.csv",header=TRUE, sep=",",dec=".",row.names=1)
Datos

Sexo EstadoCivil Nacionalidad Edad Nivel
Juan      H    Casado      Mexicano     40   1    
Hugo      H    Soltero     Mexicano     36   2    
Laura     M    Soltera     Argentina    28   1    
Ramon     H    Casado      Chileno      60   3    
Antonio   H    Casado      Uruguayo     33   3    
Sofia     M    Casada      China        29   2    
Alejandra M    Soltera     Alemana      44   1    
Alfredo   H    Soltero     Uruguayo     53   1    
Romina    M    Casada      Chilena      38   2    
Felipe    H    Casado      Mexicano     28   2

Como puede observarse, la variable nivel, la está leyendo como varible numérica, pero en realidad es una varible categórica, para corregir esta lectura se debe utilizar el parámetro colClasses para que la lectura sea la adecuada, como se muestra a acontinuación:


In [51]:
## Vamos a establecer el directorio
setwd("/home/jovyan/work/tratamiento")


Datos<-read.table("Empleados.csv",header=TRUE, sep=",",dec=".",row.names=1, colClasses = c("Nivel"="factor"))

str(Datos)

'data.frame':	10 obs. of  5 variables:
 $ Sexo        : Factor w/ 2 levels "H","M": 1 1 2 1 1 2 2 1 2 1
 $ EstadoCivil : Factor w/ 4 levels "Casada","Casado",..: 2 4 3 2 2 1 3 4 1 2
 $ Nacionalidad: Factor w/ 7 levels "Alemana","Argentina",..: 6 6 2 4 7 5 1 7 3 6
 $ Edad        : int  40 36 28 60 33 29 44 53 38 28
 $ Nivel       : Factor w/ 3 levels "1","2","3": 1 2 1 3 3 2 1 1 2 2


In [52]:
## Mostrar los datos de la fila 1
Datos[1,]

Sexo EstadoCivil Nacionalidad Edad Nivel
Juan H    Casado      Mexicano     40   1

In [53]:
## Los empleados del nivel 2
DatosNivel2<-Datos[,4]>=40
Datos[DatosNivel2,]

Sexo EstadoCivil Nacionalidad Edad Nivel
Juan      H    Casado      Mexicano     40   1    
Ramon     H    Casado      Chileno      60   3    
Alejandra M    Soltera     Alemana      44   1    
Alfredo   H    Soltero     Uruguayo     53   1

 Otra forma de trabajar con las variables de los Data Frames, es poniendo el nombre de la hoja seguido del símbolo $ y del nombre de la variable.


In [54]:
## Mostrar los datos de la fila 1
Datos$EstadoCivil

[1] Casado  Soltero Soltera Casado  Casado  Casada  Soltera Soltero Casada 
[10] Casado 
Levels: Casada Casado Soltera Soltero

In [55]:
## Los empleados del nivel 2
mean(Datos$Edad)

[1] 38.9